### ISSUE TITLE
Error "Unknown packetName"

### ISSUE THREAD

**Issue by gaudes** [ioBroker/testing-action-adapter#1]
Hi,

I have an adapter "slideshow". When running the workflow test-and-release I get the following error on test:integration:

```
2022-08-01T19:28:11.486Z testing:integration:AdapterSetup Removing old adapter instances...
2022-08-01T19:28:11.488Z testing:integration:AdapterSetup   => done!
2022-08-01T19:28:11.488Z testing:integration:AdapterSetup Adding adapter instance...
host.fv-az108-137 Unknown packetName slideshow. Please install packages from outside the repository using npm!
    1) "before all" hook: prepareTests in "Adapter integration tests"


  0 passing (37s)
  1 failing

  1) Adapter integration tests
       "before all" hook: prepareTests in "Adapter integration tests":
     Error: Adding the adapter instance failed!
      at AdapterSetup.addAdapterInstance (node_modules/@iobroker/testing/build/tests/integration/lib/adapterSetup.js:118:19)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Context.prepareTests (node_modules/@iobroker/testing/build/tests/integration/index.js:71:9)
```

When running locally the `npm run test:integration` it works.

Any ideas ?

Thanks and regards, Ralf

**Comment by Apollon77** [comment]
it is not installed at all?
https://github.com/gaudes/ioBroker.slideshow/runs/7618487751?check_suite_focus=true#step:2:607

**Comment by gaudes** [comment]
No, see complete attached log file
[git.txt](https://github.com/ioBroker/testing-action-adapter/files/9240013/git.txt)

**Comment by Apollon77** [comment]
Yes I repeat it :-))

> 2022-08-01T19:28:11.1373013Z npm ERR! code ENOTSUP
2022-08-01T19:28:11.1408672Z npm ERR! notsup Unsupported engine for image-size@1.0.2: wanted: {"node":">=14.0.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
2022-08-01T19:28:11.1409857Z npm ERR! notsup Not compatible with your version of node/npm: image-size@1.0.2
2022-08-01T19:28:11.1410787Z npm ERR! notsup Not compatible with your version of node/npm: image-size@1.0.2
2022-08-01T19:28:11.1412973Z npm ERR! notsup Required: {"node":">=14.0.0"}
2022-08-01T19:28:11.1413583Z npm ERR! notsup Actual:   {"npm":"6.14.16","node":"12.22.12"}
2022-08-01T19:28:11.1443779Z 
2022-08-01T19:28:11.1444617Z npm ERR! A complete log of this run can be found in:
2022-08-01T19:28:11.1445503Z npm ERR!     /home/runner/.npm/_logs/2022-08-01T19_28_11_141Z-debug.log

That usually means that the "nopm install" was not successfull ... so in fact "the adapter was NOT installed".

Seems that this library needs nodejs 14+ ... so testing on Nodejs 12 is useless

**Comment by gaudes** [comment]
Thanks you. The trees, the forrest, .... 

I removed support for node 12.

Best wishes, Ralf

**Comment by Apollon77** [comment]
simply say "too warm" ... anyone will understand these days

**Comment by AlCalzone** [comment]
I guess the forest will say the same "too warm, too dry" ;)
